@startuml

title __SENTIMENT's Class Diagram__\n

  namespace com.pullenti.ner {
    namespace sentiment {
      class com.pullenti.ner.sentiment.SentimentAnalyzer {
          {static} + ANALYZER_NAME : String
          {static} - m_Inited : boolean
          {static} - m_Termins : TerminCollection
          + SentimentAnalyzer()
          + clone()
          + createAnalyzerData()
          + createReferent()
          + getCaption()
          + getDescription()
          + getImages()
          + getName()
          + getProgressWeight()
          + getTypeSystem()
          + getUsedExternObjectTypes()
          {static} + initialize()
          + isSpecific()
          + process()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace sentiment {
      class com.pullenti.ner.sentiment.SentimentKind {
          {static} + NEGATIVE : SentimentKind
          {static} + POSITIVE : SentimentKind
          {static} + UNDEFINED : SentimentKind
          {static} - m_Keys : Collection<Integer>
          {static} - m_Values : SentimentKind[]
          - m_str : String
          - m_val : int
          {static} - mapIntToEnum : HashMap<Integer, SentimentKind>
          {static} - mapStringToEnum : HashMap<String, SentimentKind>
          + compareTo()
          {static} + getValues()
          + hashCode()
          {static} + isDefined()
          {static} + of()
          {static} + of()
          + toString()
          + value()
          - SentimentKind()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace sentiment {
      class com.pullenti.ner.sentiment.SentimentReferent {
          {static} + ATTR_COEF : String
          {static} + ATTR_KIND : String
          {static} + ATTR_REF : String
          {static} + ATTR_SPELLING : String
          {static} + OBJ_TYPENAME : String
          + SentimentReferent()
          + canBeEquals()
          + canBeGeneralFor()
          + createOntologyItem()
          + getCoef()
          + getKind()
          + getSpelling()
          + setCoef()
          + setKind()
          + setSpelling()
          + toString()
      }
    }
  }
  

  com.pullenti.ner.sentiment.SentimentAnalyzer -up-|> com.pullenti.ner.Analyzer
  com.pullenti.ner.sentiment.SentimentKind .up.|> java.lang.Comparable
  com.pullenti.ner.sentiment.SentimentReferent -up-|> com.pullenti.ner.Referent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
