@startuml

title __INTERNAL's Class Diagram__\n

  namespace com.pullenti.ner {
    namespace definition {
      namespace internal {
        class com.pullenti.ner.definition.internal.DefinitionAnalyzerEn {
            + DefinitionAnalyzerEn()
            {static} + process()
            {static} - tryParseThesis()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace definition {
      namespace internal {
        class com.pullenti.ner.definition.internal.MetaDefin {
            {static} + IMAGEASSID : String
            {static} + IMAGEDEFID : String
            {static} + globalMeta : MetaDefin
            + MetaDefin()
            + getCaption()
            + getImageId()
            + getName()
            {static} + initialize()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace definition {
      namespace internal {
        class com.pullenti.ner.definition.internal.ParenthesisToken {
            {static} - m_Termins : TerminCollection
            + ParenthesisToken()
            + ParenthesisToken()
            {static} + _new1136()
            {static} + initialize()
            {static} + tryAttach()
        }
      }
    }
  }
  

  com.pullenti.ner.definition.internal.MetaDefin -up-|> com.pullenti.ner.ReferentClass
  com.pullenti.ner.definition.internal.ParenthesisToken -up-|> com.pullenti.ner.MetaToken
  com.pullenti.ner.definition.internal.ParenthesisToken o-- com.pullenti.ner.Referent : ref


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
