@startuml

title __INTERNAL's Class Diagram__\n

  namespace com.pullenti.ner {
    namespace goods {
      namespace internal {
        class com.pullenti.ner.goods.internal.AttrMeta {
            {static} + ATTRIMAGEID : String
            {static} + GLOBALMETA : AttrMeta
            + AttrMeta()
            + getCaption()
            + getImageId()
            + getName()
            {static} + initialize()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace goods {
      namespace internal {
        class com.pullenti.ner.goods.internal.GoodAttrToken {
            + altValue : String
            + name : String
            + value : String
            {static} - m_DenomAn : DenominationAnalyzer
            {static} - m_Inited : boolean
            {static} - m_NumSuff : TerminCollection
            {static} - m_StdAbbrs : TerminCollection
            + GoodAttrToken()
            + GoodAttrToken()
            + _createAttr()
            {static} + _new1295()
            {static} + _new1296()
            {static} + _new1297()
            {static} + _new1299()
            {static} + _new1300()
            {static} + _new1301()
            {static} + _new1303()
            {static} + _new1305()
            {static} + _new1313()
            {static} + _new1336()
            {static} + initialize()
            + toString()
            {static} + tryParse()
            {static} + tryParseList()
            {static} - _isSpecVerb()
            {static} - _tryParseChars()
            {static} - _tryParseList()
            {static} - _tryParseModel()
            {static} - _tryParseNum()
            {static} - _tryParseNum2()
            {static} - _tryParse_()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace goods {
      namespace internal {
        class com.pullenti.ner.goods.internal.GoodMeta {
            {static} + GLOBALMETA : GoodMeta
            {static} + IMAGEID : String
            + GoodMeta()
            + getCaption()
            + getImageId()
            + getName()
            {static} + initialize()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace goods {
      namespace internal {
        class com.pullenti.ner.goods.internal.ResourceHelper {
            + ResourceHelper()
            {static} + getBytes()
            {static} + getString()
        }
      }
    }
  }
  

  com.pullenti.ner.goods.internal.AttrMeta -up-|> com.pullenti.ner.ReferentClass
  com.pullenti.ner.goods.internal.AttrMeta o-- com.pullenti.ner.Feature : typAttr
  com.pullenti.ner.goods.internal.GoodAttrToken -up-|> com.pullenti.ner.MetaToken
  com.pullenti.ner.goods.internal.GoodAttrToken o-- com.pullenti.ner.Referent : ref
  com.pullenti.ner.goods.internal.GoodAttrToken o-- com.pullenti.ner.ReferentToken : refTok
  com.pullenti.ner.goods.internal.GoodAttrToken o-- com.pullenti.ner.goods.GoodAttrType : typ
  com.pullenti.ner.goods.internal.GoodMeta -up-|> com.pullenti.ner.ReferentClass


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
