@startuml

title __INTERNAL's Class Diagram__\n

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.FioTemplateType {
            {static} + ASIANNAME : FioTemplateType
            {static} + ASIANSURNAMENAME : FioTemplateType
            {static} + IISURNAME : FioTemplateType
            {static} + ISURNAME : FioTemplateType
            {static} + KING : FioTemplateType
            {static} + NAMEISURNAME : FioTemplateType
            {static} + NAMESECNAME : FioTemplateType
            {static} + NAMESECNAMESURNAME : FioTemplateType
            {static} + NAMESURNAME : FioTemplateType
            {static} + SURNAMEI : FioTemplateType
            {static} + SURNAMEII : FioTemplateType
            {static} + SURNAMENAME : FioTemplateType
            {static} + SURNAMENAMESECNAME : FioTemplateType
            {static} + UNDEFINED : FioTemplateType
            {static} - m_Keys : Collection<Integer>
            {static} - m_Values : FioTemplateType[]
            - m_str : String
            - m_val : int
            {static} - mapIntToEnum : HashMap<Integer, FioTemplateType>
            {static} - mapStringToEnum : HashMap<String, FioTemplateType>
            + compareTo()
            {static} + getValues()
            + hashCode()
            {static} + isDefined()
            {static} + of()
            {static} + of()
            + toString()
            + value()
            - FioTemplateType()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.MetaPerson {
            {static} + ATTR_SEXFEMALE : String
            {static} + ATTR_SEXMALE : String
            {static} + GENERALIMAGEID : String
            {static} + MANIMAGEID : String
            {static} + PERSONIMAGEID : String
            {static} + WOMENIMAGEID : String
            {static} + globalMeta : MetaPerson
            + MetaPerson()
            + getCaption()
            + getImageId()
            + getName()
            {static} + initialize()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.MetaPersonIdentity {
            {static} + IMAGEID : String
            {static} + globalMeta : MetaPersonIdentity
            + MetaPersonIdentity()
            + getCaption()
            + getImageId()
            + getName()
            {static} + initialize()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.MetaPersonProperty {
            {static} + PERSONPROPBOSSIMAGEID : String
            {static} + PERSONPROPIMAGEID : String
            {static} + PERSONPROPKINGIMAGEID : String
            {static} + PERSONPROPKINIMAGEID : String
            {static} + PERSONPROPMILITARYID : String
            {static} + PERSONPROPNATIONID : String
            {static} + globalMeta : MetaPersonProperty
            + MetaPersonProperty()
            + getCaption()
            + getImageId()
            + getName()
            {static} + initialize()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonAttrTermin {
            + canBeIndependant : boolean
            + canBeSameSurname : boolean
            + canBeUniqueIdentifier : boolean
            + canHasPersonAfter : int
            + isBoss : boolean
            + isDoubt : boolean
            + isKin : boolean
            + isMilitaryRank : boolean
            + isNation : boolean
            + PersonAttrTermin()
            + PersonAttrTermin()
            {static} + _new2407()
            {static} + _new2408()
            {static} + _new2409()
            {static} + _new2410()
            {static} + _new2418()
            {static} + _new2419()
            {static} + _new2424()
            {static} + _new2425()
            {static} + _new2444()
            {static} + _new2446()
            {static} + _new2451()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonAttrTerminType {
            {static} + BESTREGARDS : PersonAttrTerminType
            {static} + KING : PersonAttrTerminType
            {static} + OTHER : PersonAttrTerminType
            {static} + POSITION : PersonAttrTerminType
            {static} + PREFIX : PersonAttrTerminType
            {static} - m_Keys : Collection<Integer>
            {static} - m_Values : PersonAttrTerminType[]
            - m_str : String
            - m_val : int
            {static} - mapIntToEnum : HashMap<Integer, PersonAttrTerminType>
            {static} - mapStringToEnum : HashMap<String, PersonAttrTerminType>
            + compareTo()
            {static} + getValues()
            + hashCode()
            {static} + isDefined()
            {static} + of()
            {static} + of()
            + toString()
            + value()
            - PersonAttrTerminType()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonAttrTerminType2 {
            {static} + ABBR : PersonAttrTerminType2
            {static} + ADJ : PersonAttrTerminType2
            {static} + GRADE : PersonAttrTerminType2
            {static} + IGNOREDADJ : PersonAttrTerminType2
            {static} + IO : PersonAttrTerminType2
            {static} + IO2 : PersonAttrTerminType2
            {static} + UNDEFINED : PersonAttrTerminType2
            {static} - m_Keys : Collection<Integer>
            {static} - m_Values : PersonAttrTerminType2[]
            - m_str : String
            - m_val : int
            {static} - mapIntToEnum : HashMap<Integer, PersonAttrTerminType2>
            {static} - mapStringToEnum : HashMap<String, PersonAttrTerminType2>
            + compareTo()
            {static} + getValues()
            + hashCode()
            {static} + isDefined()
            {static} + of()
            {static} + of()
            + toString()
            + value()
            - PersonAttrTerminType2()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonAttrToken {
            {static} + _globalInstance : PersonAttrToken
            + addOuterOrgAsRef : boolean
            + age : String
            + canBeSameSurname : boolean
            + canBeSinglePerson : boolean
            + canHasPersonAfter : int
            + isDoubt : boolean
            + value : String
            - m_CanBeIndependentProperty : boolean
            {static} - m_EmptyAdjs : String[]
            {static} - m_StdForms : HashMap<String, ArrayList<MorphWordForm>>
            {static} - m_TerminVrio : PersonAttrTermin
            {static} - m_Termins : TerminCollection
            {static} - objNameAddr : String
            {static} - objNameDate : String
            {static} - objNameDateRange : String
            {static} - objNameGeo : String
            {static} - objNameOrg : String
            {static} - objNameTransport : String
            + PersonAttrToken()
            + PersonAttrToken()
            {static} + _new2452()
            {static} + _new2453()
            {static} + _new2457()
            {static} + _new2459()
            {static} + _new2461()
            {static} + _new2467()
            {static} + _new2470()
            {static} + _new2476()
            {static} + _new2488()
            {static} + _new2491()
            + canBeIndependentProperty()
            {static} + checkKind()
            + getPropRef()
            {static} + initialize()
            + saveToLocalOntology()
            + setBeIndependentProperty()
            + setPropRef()
            + toString()
            {static} + tryAttach()
            {static} + tryAttachPositionWord()
            {static} + tryAttachWord()
            {static} - _TryAttach()
            {static} - _analizeVise()
            {static} - _existsInDoctionary()
            {static} - _findGradeLast()
            {static} - _isPerson()
            {static} - createAttrGrade()
            {static} - createAttrPosition()
            {static} - deflate()
            {static} - getStdForms()
            {static} - loadAttrs()
            {static} - tryAttachCategory()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonAttrToken.PersonAttrAttachAttrs {
            {static} + AFTERZAMESTITEL : PersonAttrAttachAttrs
            {static} + INPROCESS : PersonAttrAttachAttrs
            {static} + NO : PersonAttrAttachAttrs
            {static} + ONLYKEYWORD : PersonAttrAttachAttrs
            {static} - m_Keys : Collection<Integer>
            {static} - m_Values : PersonAttrAttachAttrs[]
            - m_str : String
            - m_val : int
            {static} - mapIntToEnum : HashMap<Integer, PersonAttrAttachAttrs>
            {static} - mapStringToEnum : HashMap<String, PersonAttrAttachAttrs>
            + compareTo()
            {static} + getValues()
            + hashCode()
            {static} + isDefined()
            {static} + of()
            {static} + of()
            + toString()
            + value()
            - PersonAttrAttachAttrs()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonHelper {
            + PersonHelper()
            {static} + createNickname()
            {static} + createReferentToken()
            {static} + createSex()
            {static} + isPersonSayOrAttrAfter()
            {static} - correctTailAttributes()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonIdToken {
            {static} + _globalInstance : PersonIdToken
            + hasPrefix : boolean
            + value : String
            {static} - m_Ontology : TerminCollection
            + PersonIdToken()
            + PersonIdToken()
            {static} + _new2513()
            {static} + _new2515()
            {static} + _new2516()
            {static} + initialize()
            {static} + tryAttach()
            {static} - tryParse()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonIdToken.Typs {
            {static} + ADDRESS : Typs
            {static} + CODE : Typs
            {static} + DATE : Typs
            {static} + KEYWORD : Typs
            {static} + NUMBER : Typs
            {static} + ORG : Typs
            {static} + SERIA : Typs
            {static} + VIDAN : Typs
            {static} - m_Keys : Collection<Integer>
            {static} - m_Values : Typs[]
            - m_str : String
            - m_val : int
            {static} - mapIntToEnum : HashMap<Integer, Typs>
            {static} - mapStringToEnum : HashMap<String, Typs>
            + compareTo()
            {static} + getValues()
            + hashCode()
            {static} + isDefined()
            {static} + of()
            {static} + of()
            + toString()
            + value()
            - Typs()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonIdentityToken {
            + coef : float
            + middlename : Object
            + PersonIdentityToken()
            + PersonIdentityToken()
            {static} + _new2498()
            {static} + checkLatinAfter()
            {static} + correctXFML()
            {static} + createLastname()
            {static} + createTyp()
            + getProbableGender()
            {static} + manageFirstname()
            {static} + manageLastname()
            {static} + sort()
            + toString()
            {static} + tryAttach()
            {static} + tryAttachForExtOnto()
            {static} + tryAttachIdentity()
            {static} + tryAttachLatinSurname()
            {static} + tryAttachOntoExt()
            {static} + tryAttachOntoForDuble()
            {static} + tryAttachOntoForSingle()
            {static} + tryAttachOntoInt()
            {static} - _TryAttachOnto()
            {static} - _calcCoefAfter()
            {static} - accordMorph()
            {static} - correctCoefAfterLastname()
            {static} - correctCoefAfterName()
            {static} - correctCoefForLastname()
            {static} - correctCoefSNS()
            {static} - getValue()
            {static} - isAccords()
            {static} - isBothSurnames()
            {static} - manageMiddlename()
            {static} - setValue()
            {static} - setValue2()
            {static} - tryAttachAsian()
            {static} - tryAttachGlobal()
            {static} - tryAttachIISurname()
            {static} - tryAttachKing()
            {static} - tryAttachNameSecname()
            {static} - tryAttachNameSecnameSurname()
            {static} - tryAttachNameSurname()
            {static} - tryAttachSingleSurname()
            {static} - tryAttachSurnameII()
            {static} - tryAttachSurnameName()
            {static} - tryAttachSurnameNameSecname()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonItemToken {
            {static} + M_ARABPOSTFIX : ArrayList<String>
            {static} + M_ARABPOSTFIXFEM : ArrayList<String>
            {static} + M_SURPREFIXES : ArrayList<String>
            {static} + _globalInstance : PersonItemToken
            + isHiphenAfter : boolean
            + isHiphenBefore : boolean
            + isInDictionary : boolean
            + value : String
            {static} - m_SurPrefixesLat : ArrayList<String>
            + PersonItemToken()
            {static} + _new2534()
            {static} + _new2536()
            {static} + _new2542()
            {static} + _new2550()
            {static} + _new2565()
            {static} + _new2566()
            {static} + _new2567()
            {static} + initialize()
            + isAsianItem()
            + mergeWithByHiphen()
            + removeNotGenitive()
            + toString()
            {static} + tryAttach()
            {static} + tryAttachLatin()
            {static} + tryAttachList()
            {static} + tryParsePerson()
            - PersonItemToken()
            {static} - _tryAttach()
            - addPostfixInfo()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonItemToken.ItemType {
            {static} + INITIAL : ItemType
            {static} + REFERENT : ItemType
            {static} + SUFFIX : ItemType
            {static} + VALUE : ItemType
            {static} - m_Keys : Collection<Integer>
            {static} - m_Values : ItemType[]
            - m_str : String
            - m_val : int
            {static} - mapIntToEnum : HashMap<Integer, ItemType>
            {static} - mapStringToEnum : HashMap<String, ItemType>
            + compareTo()
            {static} + getValues()
            + hashCode()
            {static} + isDefined()
            {static} + of()
            {static} + of()
            + toString()
            + value()
            - ItemType()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItem {
            + isHasStdPostfix : boolean
            + isInDictionary : boolean
            + isInOntology : boolean
            + isLastnameHasHiphen : boolean
            + isLastnameHasStdTail : boolean
            + term : String
            + vars : ArrayList<MorphPersonItemVariant>
            {static} - m_LastnameAsian : ArrayList<String>
            {static} - m_LastnameStdTails : ArrayList<SurnameTail>
            {static} - m_LatsnameSexStdTails : ArrayList<String>
            + MorphPersonItem()
            {static} + _new2532()
            {static} + _new2540()
            {static} + _new2543()
            {static} + _new2574()
            + addPostfix()
            + addPrefix()
            + correctLastnameVariants()
            {static} + endsWithStdSurname()
            + getMorph()
            {static} + initialize()
            + isChinaSurname()
            + mergeHiphen()
            + mergeWithByHiphen()
            + removeNotGenitive()
            + toString()
            {static} - findTail()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItemVariant {
            + shortValue : String
            + value : String
            + MorphPersonItemVariant()
            + MorphPersonItemVariant()
            {static} + _new2584()
            + toString()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonItemToken.ParseAttr {
            {static} + ALTVAR : ParseAttr
            {static} + CANBELATIN : ParseAttr
            {static} + CANBELOWER : ParseAttr
            {static} + CANINITIALBEDIGIT : ParseAttr
            {static} + IGNOREATTRS : ParseAttr
            {static} + MUSTBEITEMALWAYS : ParseAttr
            {static} + NO : ParseAttr
            {static} + NOMINATIVECASE : ParseAttr
            {static} + SURNAMEPREFIXNOTMERGE : ParseAttr
            {static} - m_Keys : Collection<Integer>
            {static} - m_Values : ParseAttr[]
            - m_str : String
            - m_val : int
            {static} - mapIntToEnum : HashMap<Integer, ParseAttr>
            {static} - mapStringToEnum : HashMap<String, ParseAttr>
            + compareTo()
            {static} + getValues()
            + hashCode()
            {static} + isDefined()
            {static} + of()
            {static} + of()
            + toString()
            + value()
            - ParseAttr()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonItemToken.SurnameTail {
            + tail : String
            + SurnameTail()
            + SurnameTail()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonMorphCollection {
            {static} + _globalInstance : PersonMorphCollection
            + head : String
            + items : ArrayList<PersonMorphVariant>
            + number : int
            {static} - m_Comparer : SortComparer
            + PersonMorphCollection()
            + add()
            {static} + addPrefix()
            + addPrefixStr()
            + checkLatinVariant()
            + correct()
            + getGender()
            + getHasLastnameStandardTail()
            + getValues()
            {static} + intersect()
            {static} + isEquals()
            + remove()
            {static} + setGender()
            + toString()
            - containsItem()
            {static} - intersect2()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonMorphCollection.PersonMorphVariant {
            + shortValue : String
            + value : String
            + PersonMorphVariant()
            {static} + _new2598()
            + toString()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonMorphCollection.SortComparer {
            + SortComparer()
            + compare()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.PersonPropAnalyzer {
            {static} + ANALYZER_NAME : String
            + PersonPropAnalyzer()
            + clone()
            + getCaption()
            + getName()
            + processReferent()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.ResourceHelper {
            + ResourceHelper()
            {static} + getBytes()
            {static} + getString()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.ShortNameHelper {
            {static} + _globalInstance : ShortNameHelper
            {static} - m_Inited : boolean
            {static} - m_Shorts_Names : HashMap<String, ArrayList<ShortnameVar>>
            + ShortNameHelper()
            {static} + getNamesForShortname()
            {static} + getShortnamesForName()
            {static} + initialize()
        }
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace person {
      namespace internal {
        class com.pullenti.ner.person.internal.ShortNameHelper.ShortnameVar {
            + name : String
            + ShortnameVar()
            {static} + _new2605()
            + toString()
        }
      }
    }
  }
  

  com.pullenti.ner.person.internal.FioTemplateType .up.|> java.lang.Comparable
  com.pullenti.ner.person.internal.MetaPerson -up-|> com.pullenti.ner.ReferentClass
  com.pullenti.ner.person.internal.MetaPersonIdentity -up-|> com.pullenti.ner.ReferentClass
  com.pullenti.ner.person.internal.MetaPersonProperty -up-|> com.pullenti.ner.ReferentClass
  com.pullenti.ner.person.internal.PersonAttrTermin -up-|> com.pullenti.ner.core.Termin
  com.pullenti.ner.person.internal.PersonAttrTermin o-- com.pullenti.ner.person.internal.PersonAttrTerminType : typ
  com.pullenti.ner.person.internal.PersonAttrTermin o-- com.pullenti.ner.person.internal.PersonAttrTerminType2 : typ2
  com.pullenti.ner.person.internal.PersonAttrTerminType .up.|> java.lang.Comparable
  com.pullenti.ner.person.internal.PersonAttrTerminType2 .up.|> java.lang.Comparable
  com.pullenti.ner.person.internal.PersonAttrToken -up-|> com.pullenti.ner.ReferentToken
  com.pullenti.ner.person.internal.PersonAttrToken o-- com.pullenti.ner.Token : anafor
  com.pullenti.ner.person.internal.PersonAttrToken o-- com.pullenti.morph.MorphGender : gender
  com.pullenti.ner.person.internal.PersonAttrToken o-- com.pullenti.ner.person.internal.PersonAttrToken : higherPropRef
  com.pullenti.ner.person.internal.PersonAttrToken o-- com.pullenti.ner.person.internal.PersonItemToken : kingSurname
  com.pullenti.ner.person.internal.PersonAttrToken o-- com.pullenti.ner.person.internal.PersonAttrTerminType : typ
  com.pullenti.ner.person.internal.PersonAttrToken +-down- com.pullenti.ner.person.internal.PersonAttrToken.PersonAttrAttachAttrs
  com.pullenti.ner.person.internal.PersonAttrToken.PersonAttrAttachAttrs .up.|> java.lang.Comparable
  com.pullenti.ner.person.internal.PersonIdToken -up-|> com.pullenti.ner.MetaToken
  com.pullenti.ner.person.internal.PersonIdToken o-- com.pullenti.ner.Referent : referent
  com.pullenti.ner.person.internal.PersonIdToken o-- com.pullenti.ner.person.internal.PersonIdToken.Typs : typ
  com.pullenti.ner.person.internal.PersonIdToken +-down- com.pullenti.ner.person.internal.PersonIdToken.Typs
  com.pullenti.ner.person.internal.PersonIdToken.Typs .up.|> java.lang.Comparable
  com.pullenti.ner.person.internal.PersonIdentityToken -up-|> com.pullenti.ner.MetaToken
  com.pullenti.ner.person.internal.PersonIdentityToken o-- com.pullenti.ner.person.internal.PersonMorphCollection : firstname
  com.pullenti.ner.person.internal.PersonIdentityToken o-- com.pullenti.ner.person.internal.PersonMorphCollection : lastname
  com.pullenti.ner.person.internal.PersonIdentityToken o-- com.pullenti.ner.person.PersonReferent : ontologyPerson
  com.pullenti.ner.person.internal.PersonIdentityToken o-- com.pullenti.ner.person.internal.FioTemplateType : typ
  com.pullenti.ner.person.internal.PersonItemToken -up-|> com.pullenti.ner.MetaToken
  com.pullenti.ner.person.internal.PersonItemToken o-- com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItem : firstname
  com.pullenti.ner.person.internal.PersonItemToken o-- com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItem : lastname
  com.pullenti.ner.person.internal.PersonItemToken o-- com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItem : middlename
  com.pullenti.ner.person.internal.PersonItemToken o-- com.pullenti.ner.person.PersonReferent : referent
  com.pullenti.ner.person.internal.PersonItemToken o-- com.pullenti.ner.person.internal.PersonItemToken.ItemType : typ
  com.pullenti.ner.person.internal.PersonItemToken +-down- com.pullenti.ner.person.internal.PersonItemToken.ItemType
  com.pullenti.ner.person.internal.PersonItemToken +-down- com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItem
  com.pullenti.ner.person.internal.PersonItemToken +-down- com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItemVariant
  com.pullenti.ner.person.internal.PersonItemToken +-down- com.pullenti.ner.person.internal.PersonItemToken.ParseAttr
  com.pullenti.ner.person.internal.PersonItemToken +-down- com.pullenti.ner.person.internal.PersonItemToken.SurnameTail
  com.pullenti.ner.person.internal.PersonItemToken.ItemType .up.|> java.lang.Comparable
  com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItem o-- com.pullenti.ner.MorphCollection : m_Morph
  com.pullenti.ner.person.internal.PersonItemToken.MorphPersonItemVariant -up-|> com.pullenti.morph.MorphBaseInfo
  com.pullenti.ner.person.internal.PersonItemToken.ParseAttr .up.|> java.lang.Comparable
  com.pullenti.ner.person.internal.PersonItemToken.SurnameTail o-- com.pullenti.morph.MorphGender : gender
  com.pullenti.ner.person.internal.PersonMorphCollection +-down- com.pullenti.ner.person.internal.PersonMorphCollection.PersonMorphVariant
  com.pullenti.ner.person.internal.PersonMorphCollection +-down- com.pullenti.ner.person.internal.PersonMorphCollection.SortComparer
  com.pullenti.ner.person.internal.PersonMorphCollection.PersonMorphVariant o-- com.pullenti.morph.MorphGender : gender
  com.pullenti.ner.person.internal.PersonMorphCollection.SortComparer .up.|> java.util.Comparator
  com.pullenti.ner.person.internal.PersonPropAnalyzer -up-|> com.pullenti.ner.Analyzer
  com.pullenti.ner.person.internal.ShortNameHelper +-down- com.pullenti.ner.person.internal.ShortNameHelper.ShortnameVar
  com.pullenti.ner.person.internal.ShortNameHelper.ShortnameVar o-- com.pullenti.morph.MorphGender : gender


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
