@startuml

title __TITLEPAGE's Class Diagram__\n

  namespace com.pullenti.ner {
    namespace titlepage {
      class com.pullenti.ner.titlepage.TitlePageAnalyzer {
          {static} + ANALYZER_NAME : String
          + TitlePageAnalyzer()
          {static} + _process()
          + clone()
          + createReferent()
          + getCaption()
          + getDescription()
          + getImages()
          + getName()
          + getProgressWeight()
          + getTypeSystem()
          {static} + initialize()
          + isSpecific()
          + process()
          + processReferent1()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace titlepage {
      class com.pullenti.ner.titlepage.TitlePageReferent {
          {static} + ATTR_AFFIRMANT : String
          {static} + ATTR_ATTR : String
          {static} + ATTR_AUTHOR : String
          {static} + ATTR_CITY : String
          {static} + ATTR_CONSULTANT : String
          {static} + ATTR_DATE : String
          {static} + ATTR_DEP : String
          {static} + ATTR_EDITOR : String
          {static} + ATTR_NAME : String
          {static} + ATTR_OPPONENT : String
          {static} + ATTR_ORG : String
          {static} + ATTR_SPECIALITY : String
          {static} + ATTR_STUDENTYEAR : String
          {static} + ATTR_SUPERVISOR : String
          {static} + ATTR_TRANSLATOR : String
          {static} + ATTR_TYPE : String
          {static} + OBJ_TYPENAME : String
          + TitlePageReferent()
          + TitlePageReferent()
          + addName()
          + addType()
          + getCity()
          + getDate()
          + getNames()
          + getOrg()
          + getSpeciality()
          + getStudentYear()
          + getTypes()
          + setCity()
          + setDate()
          + setOrg()
          + setSpeciality()
          + setStudentYear()
          + toString()
          - correctData()
      }
    }
  }
  

  com.pullenti.ner.titlepage.TitlePageAnalyzer -up-|> com.pullenti.ner.Analyzer
  com.pullenti.ner.titlepage.TitlePageReferent -up-|> com.pullenti.ner.Referent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
