@startuml

title __MAIL's Class Diagram__\n

  namespace com.pullenti.ner {
    namespace mail {
      class com.pullenti.ner.mail.MailAnalyzer {
          {static} + ANALYZER_NAME : String
          {static} - m_Inited : boolean
          + MailAnalyzer()
          + clone()
          + createReferent()
          + getCaption()
          + getDescription()
          + getImages()
          + getName()
          + getProgressWeight()
          + getTypeSystem()
          + getUsedExternObjectTypes()
          {static} + initialize()
          + isSpecific()
          + process()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace mail {
      class com.pullenti.ner.mail.MailKind {
          {static} + BODY : MailKind
          {static} + HEAD : MailKind
          {static} + HELLO : MailKind
          {static} + TAIL : MailKind
          {static} + UNDEFINED : MailKind
          {static} - m_Keys : Collection<Integer>
          {static} - m_Values : MailKind[]
          - m_str : String
          - m_val : int
          {static} - mapIntToEnum : HashMap<Integer, MailKind>
          {static} - mapStringToEnum : HashMap<String, MailKind>
          + compareTo()
          {static} + getValues()
          + hashCode()
          {static} + isDefined()
          {static} + of()
          {static} + of()
          + toString()
          + value()
          - MailKind()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace mail {
      class com.pullenti.ner.mail.MailReferent {
          {static} + ATTR_KIND : String
          {static} + ATTR_REF : String
          {static} + ATTR_TEXT : String
          {static} + OBJ_TYPENAME : String
          + MailReferent()
          {static} + _new1618()
          + addRef()
          + canBeEquals()
          + getKind()
          + getText()
          + setKind()
          + setText()
          + toString()
      }
    }
  }
  

  com.pullenti.ner.mail.MailAnalyzer -up-|> com.pullenti.ner.Analyzer
  com.pullenti.ner.mail.MailKind .up.|> java.lang.Comparable
  com.pullenti.ner.mail.MailReferent -up-|> com.pullenti.ner.Referent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
