@startuml

title __BOOKLINK's Class Diagram__\n

  namespace com.pullenti.ner {
    namespace booklink {
      class com.pullenti.ner.booklink.BookLinkAnalyzer {
          {static} + ANALYZER_NAME : String
          {static} + _globalInstance : BookLinkAnalyzer
          + BookLinkAnalyzer()
          + clone()
          + createReferent()
          + getCaption()
          + getDescription()
          + getImages()
          + getName()
          + getProgressWeight()
          + getTypeSystem()
          + getUsedExternObjectTypes()
          {static} + initialize()
          + isSpecific()
          + process()
          {static} - _addAuthor()
          {static} - tryParse()
          {static} - tryParseShortInline()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace booklink {
      class com.pullenti.ner.booklink.BookLinkAnalyzer.RegionTyp {
          {static} + AUTHORS : RegionTyp
          {static} + FIRST : RegionTyp
          {static} + NAME : RegionTyp
          {static} + SECOND : RegionTyp
          {static} + UNDEFINED : RegionTyp
          {static} - m_Keys : Collection<Integer>
          {static} - m_Values : RegionTyp[]
          - m_str : String
          - m_val : int
          {static} - mapIntToEnum : HashMap<Integer, RegionTyp>
          {static} - mapStringToEnum : HashMap<String, RegionTyp>
          + compareTo()
          {static} + getValues()
          + hashCode()
          {static} + isDefined()
          {static} + of()
          {static} + of()
          + toString()
          + value()
          - RegionTyp()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace booklink {
      class com.pullenti.ner.booklink.BookLinkRefReferent {
          {static} + ATTR_BOOK : String
          {static} + ATTR_MISC : String
          {static} + ATTR_NUMBER : String
          {static} + ATTR_PAGES : String
          {static} + ATTR_TYPE : String
          {static} + OBJ_TYPENAME : String
          + BookLinkRefReferent()
          {static} + _new406()
          + canBeEquals()
          + getBook()
          + getNumber()
          {static} + getNumberDiff()
          + getPages()
          + getParentReferent()
          + getTyp()
          + setBook()
          + setNumber()
          + setPages()
          + setTyp()
          + toString()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace booklink {
      class com.pullenti.ner.booklink.BookLinkRefType {
          {static} + INLINE : BookLinkRefType
          {static} + UNDEFINED : BookLinkRefType
          {static} - m_Keys : Collection<Integer>
          {static} - m_Values : BookLinkRefType[]
          - m_str : String
          - m_val : int
          {static} - mapIntToEnum : HashMap<Integer, BookLinkRefType>
          {static} - mapStringToEnum : HashMap<String, BookLinkRefType>
          + compareTo()
          {static} + getValues()
          + hashCode()
          {static} + isDefined()
          {static} + of()
          {static} + of()
          + toString()
          + value()
          - BookLinkRefType()
      }
    }
  }
  

  namespace com.pullenti.ner {
    namespace booklink {
      class com.pullenti.ner.booklink.BookLinkReferent {
          {static} + ATTR_AUTHOR : String
          {static} + ATTR_GEO : String
          {static} + ATTR_LANG : String
          {static} + ATTR_MISC : String
          {static} + ATTR_NAME : String
          {static} + ATTR_TYPE : String
          {static} + ATTR_URL : String
          {static} + ATTR_YEAR : String
          {static} + OBJ_TYPENAME : String
          + BookLinkReferent()
          + canBeEquals()
          + getAuthorsAndOther()
          + getLang()
          + getName()
          + getTyp()
          + getUrl()
          + getYear()
          + setAuthorsAndOther()
          + setLang()
          + setName()
          + setTyp()
          + setYear()
          + toString()
      }
    }
  }
  

  com.pullenti.ner.booklink.BookLinkAnalyzer -up-|> com.pullenti.ner.Analyzer
  com.pullenti.ner.booklink.BookLinkAnalyzer +-down- com.pullenti.ner.booklink.BookLinkAnalyzer.RegionTyp
  com.pullenti.ner.booklink.BookLinkAnalyzer.RegionTyp .up.|> java.lang.Comparable
  com.pullenti.ner.booklink.BookLinkRefReferent -up-|> com.pullenti.ner.Referent
  com.pullenti.ner.booklink.BookLinkRefType .up.|> java.lang.Comparable
  com.pullenti.ner.booklink.BookLinkReferent -up-|> com.pullenti.ner.Referent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
