@startuml

title __SQL's Class Diagram__\n

  namespace misc {
    namespace sql {
      class misc.sql.SQLCommands {
          {static} ~ conn : Connection
          {static} + addContextText()
          {static} + addEvent()
          {static} + addEventGetId()
          {static} + addKeyWord()
          {static} + addKeyWordGetId()
          {static} + addPair()
          {static} + addPerson()
          {static} + addPersonGetId()
          {static} + addPhrase()
          {static} + addSource()
          {static} + addTranslation()
          {static} + addType()
          {static} + addTypeGetId()
          {static} + addUser()
          {static} + checkContext()
          {static} + checkEvent()
          {static} + checkEventInPair()
          {static} + checkKeyWord()
          {static} + checkPair()
          {static} + checkPairPerson()
          {static} + checkPairType()
          {static} + checkPairUsingPhrase()
          {static} + checkPerson()
          {static} + checkPhrase()
          {static} + checkSource()
          {static} + checkTranslation()
          {static} + checkType()
          {static} + checkUsername()
          {static} + deleteEvent()
          {static} + deleteKeyWord()
          {static} + deletePair()
          {static} + deletePerson()
          {static} + deletePhrase()
          {static} + deleteType()
          {static} + deleteUser()
          {static} + getContextId()
          {static} + getContextIdFromPair()
          {static} + getContextText()
          {static} + getEventId()
          {static} + getEventIdFromPair()
          {static} + getEventTitle()
          {static} + getKeyWordId()
          {static} + getPairId()
          {static} + getPassword()
          {static} + getPersonId()
          {static} + getPersonIdFromPair()
          {static} + getPersonName()
          {static} + getPhrase()
          {static} + getPhraseId()
          {static} + getPhraseIdFromPair()
          {static} + getPhraseKeyWord()
          {static} + getSourceDescription()
          {static} + getSourceIdFromPair()
          {static} + getSourceIdFullCompare()
          {static} + getSourceTitle()
          {static} + getSourceURL()
          {static} + getTranslation()
          {static} + getTranslationId()
          {static} + getTranslationIdFromPair()
          {static} + getTypeId()
          {static} + getTypeIdFromPair()
          {static} + getTypeTitle()
          {static} + updatePair()
      }

      class misc.sql.SQLQueriesStore {
          {static} ~ conn : Connection
          {static} ~ jMorfSdk : JMorfSdk
          {static} + defaultList()
          {static} + filterByKeyWord()
          {static} + filterList()
          {static} + getEventList()
          {static} + getEventTitleList()
          {static} + getIdPhrasesUsingKeyWordList()
          {static} + getKeyWordList()
          {static} + getPersonList()
          {static} + getTypesList()
          {static} + getUsers()
          {static} + searchByEvent()
          {static} + searchByPerson()
          {static} + searchByPhrase()
          {static} + searchByTranslation()
          {static} + searchByType()
          {static} + searchMorphologicalEn()
          {static} + searchMorphologicalEn()
          {static} + searchMorphologicalRu()
          {static} + searchMorphologicalRu()
          {static} + setjMorfSdk()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
